import type {
  Alert,
  DisasterReport,
  EmergencyContact,
  Shelter,
} from "./types"

export const seedReports: DisasterReport[] = [
  {
    id: "rpt-1001",
    type: "Flood",
    location: "Riverside District, Chennai",
    severity: "High",
    description:
      "Heavy monsoon rains have caused the river to overflow, submerging low-lying residential areas. Several families are stranded.",
    reportedAt: "2026-06-10T08:30:00Z",
    status: "Verified",
    lat: 13.0827,
    lng: 80.2707,
  },
  {
    id: "rpt-1002",
    type: "Earthquake",
    location: "Hill Town, Shimla",
    severity: "Critical",
    description:
      "A 6.4 magnitude earthquake struck the region, causing structural damage to multiple buildings and roads.",
    reportedAt: "2026-06-11T14:05:00Z",
    status: "Verified",
    lat: 31.1048,
    lng: 77.1734,
  },
  {
    id: "rpt-1003",
    type: "Fire",
    location: "Industrial Zone, Mumbai",
    severity: "Medium",
    description:
      "A fire broke out in a chemical warehouse. Fire crews are on site and containing the spread.",
    reportedAt: "2026-06-12T19:45:00Z",
    status: "Pending",
    lat: 19.076,
    lng: 72.8777,
  },
  {
    id: "rpt-1004",
    type: "Cyclone",
    location: "Coastal Belt, Visakhapatnam",
    severity: "High",
    description:
      "Cyclone warning issued with wind speeds up to 130 km/h expected. Coastal evacuation underway.",
    reportedAt: "2026-06-12T06:15:00Z",
    status: "Verified",
    lat: 17.6868,
    lng: 83.2185,
  },
  {
    id: "rpt-1005",
    type: "Landslide",
    location: "Mountain Pass, Munnar",
    severity: "Low",
    description:
      "Minor landslide reported blocking one lane of the highway. No injuries reported.",
    reportedAt: "2026-06-09T11:20:00Z",
    status: "Resolved",
    lat: 10.0889,
    lng: 77.0595,
  },
]

export const seedAlerts: Alert[] = [
  {
    id: "alt-2001",
    title: "Critical Earthquake Aftershock Warning",
    type: "Earthquake",
    severity: "Critical",
    area: "Shimla & surrounding hill districts",
    message:
      "Strong aftershocks expected in the next 24 hours. Stay away from damaged structures and move to open ground.",
    issuedAt: "2026-06-11T15:00:00Z",
    active: true,
  },
  {
    id: "alt-2002",
    title: "Severe Flood Alert",
    type: "Flood",
    severity: "High",
    area: "Riverside District, Chennai",
    message:
      "Water levels rising rapidly. Residents in low-lying areas must evacuate to designated shelters immediately.",
    issuedAt: "2026-06-10T09:00:00Z",
    active: true,
  },
  {
    id: "alt-2003",
    title: "Cyclone Landfall Advisory",
    type: "Cyclone",
    severity: "High",
    area: "Visakhapatnam Coastal Belt",
    message:
      "Cyclone expected to make landfall within 12 hours. Fishermen advised not to venture into the sea.",
    issuedAt: "2026-06-12T07:00:00Z",
    active: true,
  },
  {
    id: "alt-2004",
    title: "Heat Wave Caution",
    type: "Fire",
    severity: "Medium",
    area: "Central Plains",
    message:
      "High temperatures increase wildfire risk. Avoid open flames and report smoke immediately.",
    issuedAt: "2026-06-08T10:00:00Z",
    active: true,
  },
  {
    id: "alt-2005",
    title: "Landslide Watch Lifted",
    type: "Landslide",
    severity: "Low",
    area: "Munnar Highway",
    message: "Road cleared and reopened. Situation back to normal.",
    issuedAt: "2026-06-09T16:00:00Z",
    active: false,
  },
]

export const seedShelters: Shelter[] = [
  {
    id: "shl-3001",
    name: "Central Community Hall",
    address: "12 MG Road, Chennai",
    capacity: 500,
    occupied: 320,
    contact: "+91 44 2345 6789",
    status: "Filling Up",
    lat: 13.0604,
    lng: 80.2496,
  },
  {
    id: "shl-3002",
    name: "Govt. High School Shelter",
    address: "45 Mall Road, Shimla",
    capacity: 300,
    occupied: 300,
    contact: "+91 177 265 4321",
    status: "Full",
    lat: 31.1033,
    lng: 77.1722,
  },
  {
    id: "shl-3003",
    name: "Coastal Relief Center",
    address: "78 Beach Road, Visakhapatnam",
    capacity: 800,
    occupied: 210,
    contact: "+91 891 278 9012",
    status: "Available",
    lat: 17.7041,
    lng: 83.3189,
  },
  {
    id: "shl-3004",
    name: "Municipal Stadium Camp",
    address: "9 Stadium Lane, Mumbai",
    capacity: 1200,
    occupied: 150,
    contact: "+91 22 2876 5432",
    status: "Available",
    lat: 19.0411,
    lng: 72.8479,
  },
  {
    id: "shl-3005",
    name: "Hill View Rest House",
    address: "3 Tea Estate Road, Munnar",
    capacity: 150,
    occupied: 40,
    contact: "+91 4865 230 111",
    status: "Available",
    lat: 10.0892,
    lng: 77.0626,
  },
]

export const emergencyContacts: EmergencyContact[] = [
  {
    id: "ec-1",
    name: "Police Control Room",
    department: "Police",
    number: "100",
    description: "Law enforcement, crime, and public safety emergencies.",
  },
  {
    id: "ec-2",
    name: "Fire & Rescue Services",
    department: "Fire Department",
    number: "101",
    description: "Fire emergencies, rescue operations, and hazardous material incidents.",
  },
  {
    id: "ec-3",
    name: "Ambulance / Medical",
    department: "Ambulance",
    number: "108",
    description: "Medical emergencies and patient transport.",
  },
  {
    id: "ec-4",
    name: "National Disaster Response Force",
    department: "Disaster Response Team",
    number: "112",
    description: "Coordinated disaster response, search, and rescue.",
  },
  {
    id: "ec-5",
    name: "Flood Control Cell",
    department: "Disaster Response Team",
    number: "1070",
    description: "State emergency operations and flood management.",
  },
  {
    id: "ec-6",
    name: "Women Helpline",
    department: "Police",
    number: "1091",
    description: "Emergency assistance for women in distress.",
  },
]
